data<-read.csv("C:\\Users\\Rohit Bora\\Documents\\exdata_data_household_power_consumption\\household_power_consumption.txt",sep=";",skip=66636,nrows = 2880,header = TRUE)
names(data)<-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
png(file="plot1.png")
hist(data$Global_active_power,col="Red",xlab="Global_active_power(kilowatts)",main="Global Active Power")
dev.off(5)
