data<-read.csv("C:\\Users\\Rohit Bora\\Documents\\exdata_data_household_power_consumption\\household_power_consumption.txt",sep=";",skip=66636,nrows = 2880,header = TRUE)
names(data)<-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
data$dt<-as.POSIXct(paste(strptime(data$Date,"%d/%m/%Y"),data$Time,sep=" "))
png(file="plot4.png")
par(mfrow=c(2,2),mar=c(4,4,4,4))
with(data,
     {  plot(data$dt,data$Global_active_power,type="l",xlab="",ylab="Global Active Power")
       plot(data$dt,data$Voltage,type="l",xlab="datetime",ylab="Voltage")
       plot(data$dt,data$Sub_metering_1,type="l",xlab="",ylab="")
       with(data,lines(dt,Sub_metering_1,type="l",col="Black"))
       with(data,lines(dt,Sub_metering_2,type="l",col="Red"))
       with(data,lines(dt,Sub_metering_3,type="l",col="Blue"))
       legend("topright",col=c("Black","Red","Blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1)
       title(ylab="Energy sub metering",xlab="")
       plot(data$dt,data$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
      }
)
dev.off(5)
dev.off(4)